//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentbuddy.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class CustomerStatu
    {
        public int Status_ID { get; set; }

        [Display(Name = "Name")]
        public int Customer_ID { get; set; }

        [Display(Name = "Time")]
        [Required]
        [DataType(DataType.Time)]
        public string Status_Time { get; set; }

        [Display(Name = "Date")]
        [Required]
        [DataType(DataType.Date)]
        public string Satus_Date { get; set; }

        [Display(Name = "Image")]
        public string Status_Image { get; set; }

        [Display(Name = "Phone")]
        [Required(ErrorMessage = "Please enter your status!")]
        public string Status { get; set; }

        public HttpPostedFileBase StatusImageFile { get; set; }


        public virtual Customer Customer { get; set; }
    }
}
